[package]
name = "zql"
version = "0.1.0"
authors = ["Byron Houwens <zhion360@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.3.1"
lazy_static = "1.4.0"
phf = { version = "0.7.24", features = ["macros"] }
